apiVersion: v1
kind: ReplicationController
metadata:
        name: nginx
spec:
        replicas: 2
        selector:
                app: nginx
        template:
                metadata:
                        name: nginx
                        lables:
                                app: nginx
                spec:
                        containers:
                                - name: nginx
                                  image: nginx
                                  ports:
                                          - containerPort: 80

